def ghid():
    print()
    print("Aveti posibilitatea sa introduceti urmatoarele comenzi:")
    print("adauga_film - adauga un nou film in lista de filme")
    print("genereaza_filme - genereaza n filme si le adauga in lista de filme")
    print("sterge_film - sterge un film existent in lista de filme")
    print("cauta_film - gaseste un film existent in lista de filme si il afiseaza")
    print("filme - afiseaza lista curenta de filme")
    print("modifica_film - inlocuieste un film existent in lista cu un alt film")
    print("adauga_client - adauga un nou client in lista de clienti")
    print("sterge_client - sterge un client existent in lista de clienti")
    print("cauta_client - gaseste un client existent in lista de clienti si il afiseaza")
    print("clienti - afiseaza lista curenta de clienti")
    print("modifica_client - inlocuieste un client existent in lista cu un alt client")
    print("inchiriaza_film - adauga o inchiriere in lista de inchirieri")
    print("returneaza_film - sterge o inchiriere din lista de inchirieri, iar filmul care face parte din inchiriere se adauga inapoi in lista de filme")
    print("modifica_inchiriere - modifica o inchiriere in cazul in care clientul din lista de clienti si-a schimbat unul dintre campurile nume sau prenume")
    print("ordoneaza_inchirieri_dupa_nume - afiseaza o copie a listei de inchirieri sortata crescator dupa numele fiecarui client (lista de inchirieri nu sufera modificari)")
    print("ordoneaza_inchirieri_dupa_filme - afiseaza o copie a listei de inchirieri sortata descrescator dupa numarul de filme pe care l-a inchiriat fiecare client (lista de inchirieri nu sufera modificari")
    print("ordoneaza_inchirieri_dupa_aparitii - afiseaza titlul fiecarui film impreuna cu numarul de inchirieri corespunzator")
    print("primii_clienti - afiseaza primii 30% clienti din lista de inchirieri si numarul de filme pe care le-au inchiriat")
    print("top_3_filme_dupa_gen - afiseaza primele 3 filme dupa gen cu cele mai multe inchirieri")
    print("inchirieri - afiseaza lista curenta de inchirieri")
    print("exit - se iese din aplicatie")
